---
- hosts: db_hosts
  vars:
    repl_user: replusr
    repl_passwd: "{{ lookup('env', 'PG_REPL_PASSWD') }}"
  remote_user: ansible
  become: True
  tasks:
  - name: Check if database is standing by
    stat:
      path: '/var/lib/pgsql/12/data/standby.signal'
    register: standby_status
  - name: Execute prequisites on all hosts
    import_tasks: pg_prequisites.yml
    when: inventory_hostname in groups['db_hosts']
  - name: Configure master node
    import_tasks: pg_conf_master.yml
    vars:
      standby_status: "{{ standby_status }}"
    when: inventory_hostname in groups['db_master']
    become_user: postgres
  - name: Configure slave nodes
    import_tasks: pg_conf_slave.yml
    when: inventory_hostname in groups['db_slaves']
    become_user: postgres
    vars:
      master_host: "{{ groups.db_master[0] }}"
  handlers:
  - name: Restart Linux server
    reboot:
  - name: Restart database
    systemd:
      state: restarted
      name: postgresql-12
      
      